
package Principal;

import Modelo.Cliente;
import Modelo.DiaDeSpa;//no entiendo donde esta mi error
import Persistencia.ClienteData;
import java.util.Date;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author franc
 */
public class DiaDeSpa extends javax.swing.JInternalFrame {

    /**
     * Creates new form DiaDeSpa
     */
    public DiaDeSpa() {
        initComponents();
        cargarClientes();
        
        SpinnerDateModel modelohora= new SpinnerDateModel();
        jshora.setModel(modelohora);
        
       // JSpinner.DateEditor editor= new JSpinner.DateEditor(jspinnerhora,"HH:mm");
        //jspinnerhora.setEditor(editor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdfecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpreferencias = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jcclientes = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jshora = new javax.swing.JSpinner();
        jRadioButton1 = new javax.swing.JRadioButton();
        jbguardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(736, 1104));

        jPanel1.setMinimumSize(new java.awt.Dimension(736, 1104));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jdfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 140, -1));

        jtpreferencias.setColumns(20);
        jtpreferencias.setRows(5);
        jScrollPane1.setViewportView(jtpreferencias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 340, 100));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, -1, -1));

        jcclientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 140, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 140, -1));
        jPanel1.add(jshora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 140, -1));

        jRadioButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jRadioButton1.setText("Activo");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, -1, -1));

        jbguardar.setText("Guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });
        jPanel1.add(jbguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 720, -1, -1));

        jButton2.setText("Salir");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 720, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sesiones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Preferencias");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DiaDeSpa.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean validarPreferencias() {
    String texto = jtpreferencias.getText().trim();

    if (texto.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "El campo no puede estar vacío.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    if (texto.length() < 5) {
        JOptionPane.showMessageDialog(this,
                "Las preferencias deben tener al menos 5 caracteres.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    if (texto.length() > 300) {
        JOptionPane.showMessageDialog(this,
                "Las preferencias no pueden superar los 300 caracteres.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Solo letras, números, acentos y signos básicos
    if (!texto.matches("[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ ,.()/-]*")) {
        JOptionPane.showMessageDialog(this,
                "Las preferencias contienen caracteres inválidos.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true; 
}

    private String obtenerPreferencias() {
    return jtpreferencias.getText().trim();
}

private boolean validarFechaHora() {

    // Validar fecha
    if (jdfecha.getDate() == null) {
        JOptionPane.showMessageDialog(this,
                "Debe seleccionar una fecha.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    // Validar hora (el spinner NO debería ser nulo nunca, pero por seguridad lo chequeamos)
    if (jshora.getValue() == null) {
        JOptionPane.showMessageDialog(this,
                "Debe seleccionar una hora válida.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true; 
}
private Timestamp obtenerFechaHora() {

    // 1) Obtener fecha del JDateChooser
    Date fechaSeleccionada = jdfecha.getDate();

    // 2) Obtener hora del JSpinner
    Date horaSeleccionada = (Date) jshora.getValue();

    // 3) Convertir fecha a LocalDate
    LocalDate fecha = fechaSeleccionada.toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalDate();

    // 4) Convertir hora a LocalTime
    LocalTime hora = horaSeleccionada.toInstant()
            .atZone(ZoneId.systemDefault())
            .toLocalTime();

    // 5) Construir LocalDateTime
    LocalDateTime fechaHora = LocalDateTime.of(fecha, hora);

    // 6) Devolver como Timestamp
    return Timestamp.valueOf(fechaHora);
}


private void cargarClientes() {
    ClienteData clienteData = new ClienteData(); 
    List<Cliente> lista = ClienteData.listarClientes(); //En mi clase Cliente Data deberia tener un metodo listar clientes verdad?

    jcclientes.removeAllItems(); // Limpia el combo por las dudas
    
    for (Cliente c : lista) {
        jcclientes.addItem(c);  // Gracias al toString mostrará nombre + apellido 
        //CONSULTA: NO PUEDO CREAR UN METODO PARECIDO AL TOSTRING QUE MUESTRE SOLO NOMBRE Y APELLIDO Y LO INVOQUE?
    }
}


    
    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

 // === Validamos datos
if (!validarPreferencias()) {return;}
if (!validarFechaHora()){return;}

// === EXTRAER datos validados
String preferencias = obtenerPreferencias();
Timestamp fechaHora = obtenerFechaHora();
Cliente cli = (Cliente) jcclientes.getSelectedItem();

 if (cli == null) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
        return;
    }

        // 5️⃣ Obtener otros datos del formulario
       // String preferencias = txtPreferencias.getText();
       // Cliente cliente = (Cliente) comboCliente.getSelectedItem();
       // if (cliente == null) {
        //    JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
        //    return;
        //}

        //double monto = Double.parseDouble(txtMonto.getText());
       // boolean estado = chkEstado.isSelected();

        // 6️⃣ Crear objeto DiaDeSpa
        DiaDeSpa dia = new DiaDeSpa();
        dia.setFechahora(fechaHora);
        dia.setPreferencias(preferencias);
        dia.setCliente(cli);
        //dia.setMonto(monto);
        //dia.setEstado(estado);

        // 7️⃣ Guardar en la base
       // diadespaData.agregarDiaDeSpa(dia);
      /* DiaDeSpaData ddd = new DiaDeSpaData();
    ddd.guardarDiaDeSpa(dia);

    JOptionPane.showMessageDialog(this, "Día de Spa guardado correctamente.");*/
}

       /* JOptionPane.showMessageDialog(this, "Día de Spa guardado correctamente.");

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Monto inválido.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
        ex.printStackTrace();*/






        // TODO add your handling code here:
    }//GEN-LAST:event_jbguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbguardar;
    private javax.swing.JComboBox<String> jcclientes;
    private com.toedter.calendar.JDateChooser jdfecha;
    private javax.swing.JSpinner jshora;
    private javax.swing.JTextArea jtpreferencias;
    // End of variables declaration//GEN-END:variables
}







