package Principal;

import Modelo.Instalacion;
import Modelo.Sesion;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

public class VistaTablaSesiones extends javax.swing.JInternalFrame {

    private List<Sesion> listaSesiones;  // atributo interno
    private DefaultTableModel modelo = new DefaultTableModel();

    public VistaTablaSesiones(List<Sesion> lista) {
        this.listaSesiones = lista;
        initComponents();
        armarCabecera();
    }

    private void inicializarTabla() {
        modelo = (DefaultTableModel) jtsesiones.getModel();
        actualizarTabla();

    }

    public void armarCabecera() {
        modelo.addColumn("IDsesion");
        modelo.addColumn("tratamiendo");
        modelo.addColumn("Masajista");
        modelo.addColumn("fechahorainicio");
        modelo.addColumn("fechahorafin");
        modelo.addColumn("instalaciones");
        modelo.addColumn("Estado");
        jtsesiones.setModel(modelo);
    
    }

    public void actualizarTabla() {
        modelo.setRowCount(0); // limpia la tabla
        for (Sesion s : listaSesiones) {
            // Concatenar nombres de instalaciones si querés mostrar todos
            String nombresInstalaciones = s.getInstalacion()
                    .stream()
                    .map(Instalacion::getNombre)
                    .collect(Collectors.joining(" - "));

            modelo.addRow(new Object[]{
                s.getIdSesion(),
                s.getTratamiento().getDetalle(), // o getNombre() según tu clase
                s.getMasajista().getNombre(),
                s.getFechaHoraInicio(),
                s.getFechaHoraFin(),
                nombresInstalaciones,
                s.isEstado() ? "Activa" : "Inactiva"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtsesiones = new javax.swing.JTable();

        jtsesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtsesiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtsesiones;
    // End of variables declaration//GEN-END:variables
}
