package Principal;

import Modelo.Instalacion;
import Modelo.Sesion;
import Persistencia.ServicioData;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

public class VistaTablaSesiones extends javax.swing.JInternalFrame {

    private List<Sesion> listaSesiones;  // atributo interno
    private DefaultTableModel modelo = new DefaultTableModel();
    ServicioData sd = new ServicioData();

    public VistaTablaSesiones(List<Sesion> lista) {
        this.listaSesiones = lista;
        initComponents();
        armarCabecera();
        inicializarTabla();
    }

    private void inicializarTabla() {
        //modelo = (DefaultTableModel) jtsesiones.getModel();
        CargarTabla();

    }

    public void armarCabecera() {
        modelo.addColumn("IDsesion");
        modelo.addColumn("tratamiendo");
        modelo.addColumn("Masajista");
        modelo.addColumn("fechahorainicio");
        modelo.addColumn("fechahorafin");
        modelo.addColumn("instalaciones");
        modelo.addColumn("Estado");
        jtsesiones.setModel(modelo);

    }

    public void CargarTabla() {
        modelo.setRowCount(0); // limpia la tabla
        for (Sesion s : listaSesiones) {
            // Concatenar nombres de instalaciones si querés mostrar todos
            String nombresInstalaciones = s.getInstalacion()
                    .stream()
                    .map(Instalacion::getNombre)
                    .collect(Collectors.joining(" - "));

            modelo.addRow(new Object[]{
                s.getIdSesion(),
                sd.buscarServicio(s.getTratamiento().getIdServicio()).getNombre(),
                s.getMasajista().getNombre(),
                s.getFechaHoraInicio(),
                s.getFechaHoraFin(),
                nombresInstalaciones,
                s.isEstado() ? "Activa" : "Inactiva"
            });
        }
    }

    public void refrescar() {
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtsesiones = new javax.swing.JTable();
        jsalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 600));

        jtsesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtsesiones.setPreferredSize(new java.awt.Dimension(500, 800));
        jScrollPane1.setViewportView(jtsesiones);

        jsalir.setText("Salir");
        jsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jsalir)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jsalir)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jsalir;
    private javax.swing.JTable jtsesiones;
    // End of variables declaration//GEN-END:variables
}
